name: Execução de testes unitários

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout projeto
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'

      - name: Install dependecies
        run: npm install

      - name: Run tests
        run: npx jest --config jest.config.ts